parameters:
  dependsOn: build_projection

jobs:

- job: sign_projection
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    name: Package ES Lab E
  steps:
  - task: DownloadBuildArtifacts@0 
    displayName: 'Download artifact: projection'
    inputs: 
      buildType: 'current'
      downloadType: single
      artifactName: projection
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - template: steps-sign-projection.yml

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: projection'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/projection
      artifactName: projection
