parameters:
  dependsOn: build_projection

jobs:

- job: download_projection
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    name: Package ES Lab E
  steps:
  - task: DownloadBuildArtifacts@0 
    displayName: 'Download artifact: projection'
    inputs: 
      buildType: 'current'
      downloadType: single
      artifactName: projection
      downloadPath: '$(Build.ArtifactStagingDirectory)'

- job: sign_projection
  dependsOn: download_projection 
  pool:
    name: Package ES Lab E
  strategy:
    maxParallel: 10
    matrix:
      Release_x86_py37:
        buildArchitecture: 'x86'
        pythonVersion: '3.7.x'
      Release_x64_py37:
        buildArchitecture: 'amd64'
        pythonVersion: '3.7.x'
      Release_x86_py38:
        buildArchitecture: 'x86'
        pythonVersion: '3.8.x'
      Release_x64_py38:
        buildArchitecture: 'amd64'
        pythonVersion: '3.8.x'

  steps:
  - template: steps-sign-projection.yml
    parameters:
      architecture: $(buildArchitecture)
      pythonVersion: $(pythonVersion)

- job: publish_projection
  dependsOn: sign_projection
  pool:
    name: Package ES Lab E

  steps:
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: projection'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/projection
      artifactName: projection
